# 多数据源SQL日志配置
spring:
  datasource:
    dynamic:
      druid:
        proxy-filters:
          - sqlLogInterceptor
# Mybatis-plus 配置
mybatis-plus:
  mapper-location: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package 用逗号或分号分割
  typeAliasesPackage: com.msop.**.model
  # 全局配置
  global-config:
    # 关闭MP 3.0 自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1：不操作 2：用户输入ID 3：数字型snowflake 4:全局唯一ID UUID 5：字符串行snowflake
      id-type: assign_id
      # 字段策略
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      # 驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值 （1 表示已删除，也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值 （0 表示未删除，也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'