# Swagger公共信息
swagger:
  title: 微服务开放平台-接口文档系统
  description: 微服务开放平台接口文档系统
  license: Powered By RUOZHULIUFENG
  license-url: https://www.aixuxi.cn
  terms-of-service-url: https://www.aixuxi.cn
  contact:
    name: ruozhuliufeng
    email: ruozhuliufeng@aixuxi.cn
    url: https://github.com/ruozhuliufeng